version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
#      - PLEX_CLAIM= #optional
    volumes:
      - /home/user/media/config:/config
      - /home/user/media/transcode:/transcode
      - /home/user/media/movies:/movies
      - /home/user/media/music:/music
    restart: unless-stopped
