version: '1'

networks:
  nginx-net:
    driver: bridge

  postgre-net:
    driver: bridge

  redis-net:
    driver: bridge

  prometheus-net:
    driver: bridge


volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "8080:80"
    links:
      - grafana
    networks:
      - nginx-net

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgresdb"
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
    expose:
      - 5432
    networks:
      - postgre-net

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - redis-net
    expose:
      - 6379

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - prometheus-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres:5432
      - GF_DATABASE_NAME=postgresdb
      - GF_DATABASE_USER=${ADMIN_USER}
      - GF_DATABASE_PASSWORD=${ADMIN_PASSWORD}
      - GF_DATABASE_SSL_MODE=disable
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DEFAULT_APP_MODE=development
      - GF_INSTALL_PLUGINS=redis-datasource
    expose:
      - 3000
    links:
      - prometheus
      - postgres
      - redis
    networks:
      - prometheus-net
      - postgre-net
      - redis-net
      - nginx-net