version: '2'
services:

 kodi:
   image: "linuxserver/kodi-headless"
   ports:
     - "8080:8080"
     - "9777:9777"
     - "9090:9090"
   environment:
     KODI_VER: 15
     TZ: "Europe/Moscow"
   links:
     - kodi-mysql:mysql
   volumes:
     #- /etc/localtime:/etc/localtime:ro
     - /home/user/media:/config/.kodi

 kodi-mysql:
   image: "tutum/mysql:5.6"
   ports:
     - "3307:3306"
   environment:
     ON_CREATE_DB: kodi_video
     MYSQL_USER: kodi
     MYSQL_PASS: kodi
     #STARTUP_SQL: /tmp/mysql-script/startup.sql
   volumes:
     # - ./config/mysql:/tmp/mysql-script
     - /home/user/media/mysql:/var/lib/mysql

 kodi-video-server:
   image: "jalle19/xbmc-video-server"
   ports:
     - "8081:80"
   links:
     - kodi:kodi
 #  volumes:
 #    - ./data/xvs/data:/src/src/protected/data
 #    - ./data/xvs/runtime:/src/src/protected/runtime
 #    - ./data/xvs/images:/src/src/images
