version: '2'
services:
  gitlab-runner:
    container_name: gitlab-runner
    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/gitlab-runner:/etc/gitlab-runner
      - /opt/gitlab-runner/data:/home/gitlab_ci_multi_runner/data
    environment:
     - CI_SERVER_URL=http://<GITLAB-CE>/ci
    restart: unless-stopped

  gitlab-ce:
    container_name: gitlab-ce
    image: 'gitlab/gitlab-ce:latest'
    volumes:
      - /etc/gitlab:/etc/gitlab
      - /var/log/gitlab:/var/log/gitlab
      - /var/opt/gitlab:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        puma['worker_processes'] = 0
        sidekiq['max_concurrency'] = 10
        prometheus_monitoring['enable'] = false
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    restart: unless-stopped
